### ISSUE TITLE
Brainstorming with Josh Stearns

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#126]
Break into individual issues the following stuff:

Bugs
* [x] #136 Issue (FYI to Chengcheng): top articles stats page is broken on online version

Small things
* [x] #127 Improve the legend (add circles for nodes, arrows for edges, bot scores all together, etc)
* [x] #128 Change "More scores" to "Update bot scores"
* [x] #129 Button color should be neutral (not blue, which is part of color scale)
* [x] #130 Label and move buttons for collapsing panes near the panes + label panes?
* [x] #135 Rename "Stats" -> "Dashboard"

Big things
* [x] #132 Temporal slider to control animation
* [x] #133 Search by URL **(hook up to Twitter Search API)** (Check MIT Media Cloud?)
* [ ] #131 Filtering nodes by bot scores
* [ ] #137 Add new dashboard that ranks top articles in our DB by inorganic amplification
* [x] #141 First-time use walkthrough (see Hamilton68)
* [x] #142 Populate search box(es) with example queries (text or article URL). Examples should be current top stories (use Google News API?)
* [x] #134 Add case studies (with 4-5 takeaways) to illustrate how to use the tool for research (linked next to Youtube tutorial on landing page). Should link to First Draft guides for social media/bot forensics (verification guides)
* [ ] #138 Browser extension for automatically submitting a link

Outreach
* [ ] #139 Reach out to individuals People at IndyStar / Erin at PolitiFact / Claire and Amy at FirstDraft (Josh will facilitate contacts)
* [ ] #140 Outreach on various forums (ONA FB page on data journalism, NICAR listserv, FirstDraft, Facebook literacy page, fakenewsci, posttruth network of Lewandoski, disinfo Google Group by NED)

**Comment by mihaivavram** [comment]
Created the issues and assigned them to whomever should work on them, the next steps are now to prioritize them, which we can do at the next meeting.

**Comment by glciampaglia** [comment]
At this point each issue is either in Launch or Utopia; closing.
