### ISSUE TITLE
Set up new database

### ISSUE THREAD

**Issue by benabus** [IUNetSci/hoaxy-botometer#5]
- [x] Determine Server that will be used to host DB #6
- [x] Install required database server software (Likely Postgresql) #7
- [x] Create DB User #8
- [x] Change DB User Password #20 
- [x] Create Database #9
- [x] Create Tables #10

**Comment by glciampaglia** [comment]
Sent request to ILS
